====================================================
Author:        AAVA
Date:          
Description:   Physical data model for Medallion Bronze Layer - mirrors source layer, includes audit, metadata, and relationships
====================================================

-- STORAGE NOTE: All tables are HEAP (no clustered index) for raw Bronze ingestion.

-- =============================
-- Bronze Layer DDL Script
-- =============================

IF OBJECT_ID('Bronze.bz_New_Monthly_HC_Report', 'U') IS NULL
CREATE TABLE Bronze.bz_New_Monthly_HC_Report (
    [id] numeric(18,0) NULL,
    [gci id] varchar(50) NULL,
    [first name] varchar(50) NULL,
    [last name] varchar(50) NULL,
    [job title] varchar(50) NULL,
    [hr_business_type] varchar(50) NULL,
    [client code] varchar(50) NULL,
    [start date] datetime NULL,
    [termdate] datetime NULL,
    [Final_End_date] datetime NULL,
    [NBR] money NULL,
    [Merged Name] varchar(100) NULL,
    [Super Merged Name] varchar(100) NULL,
    [market] varchar(50) NULL,
    [defined_New_VAS] varchar(8) NULL,
    [IS_SOW] varchar(7) NOT NULL,
    [GP] money NULL,
    [NextValue] datetime NULL,
    [termination_reason] varchar(100) NULL,
    [FirstDay] datetime NULL,
    [Emp_Status] varchar(25) NULL,
    [employee_category] varchar(50) NULL,
    [LastDay] datetime NULL,
    [ee_wf_reason] varchar(50) NULL,
    [old_Begin] numeric(2,1) NULL,
    [Begin HC] numeric(38,36) NULL,
    [Starts - New Project] numeric(38,36) NULL,
    [Starts- Internal movements] numeric(38,36) NULL,
    [Terms] numeric(38,36) NULL,
    [Other project Ends] numeric(38,36) NULL,
    [OffBoard] numeric(38,36) NULL,
    [End HC] numeric(38,36) NULL,
    [Vol_term] numeric(38,36) NULL,
    [adj] numeric(38,36) NULL,
    [YYMM] int NULL,
    [tower1] varchar(60) NULL,
    [req type] varchar(50) NULL,
    [ITSSProjectName] varchar(200) NULL,
    [IS_Offshore] varchar(20) NULL,
    [Subtier] varchar(50) NULL,
    [New_Visa_type] varchar(50) NULL,
    [Practice_type] varchar(50) NULL,
    [vertical] varchar(50) NULL,
    [CL_Group] varchar(32) NOT NULL,
    [salesrep] varchar(50) NULL,
    [recruiter] varchar(50) NULL,
    [PO_End] datetime NULL,
    [PO_End_Count] numeric(38,36) NULL,
    [Derived_Rev] real NULL,
    [Derived_GP] real NULL,
    [Backlog_Rev] real NULL,
    [Backlog_GP] real NULL,
    [Expected_Hrs] real NULL,
    [Expected_Total_Hrs] real NULL,
    [ITSS] varchar(100) NOT NULL,
    [client_entity] varchar(50) NULL,
    [newtermdate] datetime NULL,
    [Newoffboardingdate] datetime NULL,
    [HWF_Process_name] varchar(100) NULL,
    [Derived_System_End_date] datetime NULL,
    [Cons_Ageing] int NULL,
    [CP_Name] nvarchar(50) NULL,
    [bill st units] varchar(50) NULL,
    [project city] varchar(50) NULL,
    [project state] varchar(50) NULL,
    [OpportunityID] varchar(50) NULL,
    [OpportunityName] varchar(200) NULL,
    [Bus_days] real NULL,
    [circle] varchar(100) NULL,
    [community_new] varchar(100) NULL,
    [ALT] nvarchar(50) NULL,
    [Market_Leader] varchar(max) NULL,
    [Acct_Owner] nvarchar(50) NULL,
    [st_yymm] int NULL,
    [PortfolioLeader] varchar(max) NULL,
    [ClientPartner] varchar(max) NULL,
    [FP_Proj_ID] varchar(10) NULL,
    [FP_Proj_Name] varchar(max) NULL,
    [FP_TM] varchar(2) NOT NULL,
    [project_type] varchar(500) NULL,
    [FP_Proj_Planned] varchar(10) NULL,
    [Standard Job Title Horizon] nvarchar(2000) NULL,
    [Experience Level Title] varchar(200) NULL,
    [User_Name] varchar(50) NULL,
    [Status] varchar(50) NULL,
    [asstatus] varchar(50) NULL,
    [system_runtime] datetime NOT NULL,
    [BR_Start_date] datetime NULL,
    [Bill_ST] float NULL,
    [Prev_BR] float NULL,
    [ProjType] varchar(2) NOT NULL,
    [Mons_in_Same_Rate] int NULL,
    [Rate_Time_Gr] varchar(20) NULL,
    [Rate_Change_Type] varchar(20) NULL,
    [Net_Addition] numeric(38,36) NULL,
    load_timestamp DATETIME2,
    update_timestamp DATETIME2,
    source_system VARCHAR(100)
);

-- Repeat for all other tables (SchTask, Hiring_Initiator_Project_Info, Timesheet_New, report_392_all, vw_billing_timesheet_daywise_ne, vw_consultant_timesheet_daywise, DimDate, holidays_Mexico, holidays_Canada, holidays, holidays_India)

IF OBJECT_ID('Bronze.bz_SchTask', 'U') IS NULL
CREATE TABLE Bronze.bz_SchTask (
    [ID] numeric(18,0) NOT NULL,
    [SSN] varchar(50) NULL,
    [GCI_ID] varchar(50) NULL,
    [FName] varchar(50) NULL,
    [LName] varchar(50) NULL,
    [Process_ID] numeric(18,0) NOT NULL,
    [Level_ID] int NOT NULL,
    [Last_Level] int NOT NULL,
    [Initiator] varchar(50) NULL,
    [Initiator_Mail] varchar(50) NULL,
    [Status] varchar(50) NULL,
    [Comments] varchar(8000) NULL,
    [DateCreated] datetime NULL,
    [TrackID] varchar(50) NULL,
    [DateCompleted] datetime NULL,
    [Existing_Resource] varchar(3) NULL,
    [Term_ID] numeric(18,0) NULL,
    [legal_entity] varchar(50) NULL,
    [TS] timestamp NOT NULL,
    load_timestamp DATETIME2,
    update_timestamp DATETIME2,
    source_system VARCHAR(100)
);

IF OBJECT_ID('Bronze.bz_Hiring_Initiator_Project_Info', 'U') IS NULL
CREATE TABLE Bronze.bz_Hiring_Initiator_Project_Info (
    [ID] numeric(18,0) NOT NULL,
    [Candidate_LName] varchar(50) NULL,
    [Candidate_MI] varchar(50) NULL,
    [Candidate_FName] varchar(50) NULL,
    [Candidate_SSN] varchar(50) NULL,
    [HR_Candidate_JobTitle] varchar(50) NULL,
    [HR_Candidate_JobDescription] varchar(100) NULL,
    [HR_Candidate_DOB] varchar(50) NULL,
    [HR_Candidate_Employee_Type] varchar(50) NULL,
    [HR_Project_Referred_By] varchar(50) NULL,
    [HR_Project_Referral_Fees] varchar(50) NULL,
    [HR_Project_Referral_Units] varchar(50) NULL,
    [HR_Relocation_Request] varchar(50) NULL,
    [HR_Relocation_departure_city] varchar(50) NULL,
    [HR_Relocation_departure_state] varchar(50) NULL,
    [HR_Relocation_departure_airport] varchar(50) NULL,
    [HR_Relocation_departure_date] varchar(50) NULL,
    [HR_Relocation_departure_time] varchar(50) NULL,
    [HR_Relocation_arrival_city] varchar(50) NULL,
    [HR_Relocation_arrival_state] varchar(50) NULL,
    [HR_Relocation_arrival_airport] varchar(50) NULL,
    [HR_Relocation_arrival_date] varchar(50) NULL,
    [HR_Relocation_arrival_time] varchar(50) NULL,
    [HR_Relocation_AccomodationStartDate] varchar(50) NULL,
    [HR_Relocation_AccomodationEndDate] varchar(50) NULL,
    [HR_Relocation_AccomodationStartTime] varchar(50) NULL,
    [HR_Relocation_AccomodationEndTime] varchar(50) NULL,
    [HR_Relocation_CarPickup_Place] varchar(50) NULL,
    [HR_Relocation_CarPickup_AddressLine1] varchar(50) NULL,
    [HR_Relocation_CarPickup_AddressLine2] varchar(50) NULL,
    [HR_Relocation_CarPickup_City] varchar(50) NULL,
    [HR_Relocation_CarPickup_State] varchar(50) NULL,
    [HR_Relocation_CarPickup_Zip] varchar(50) NULL,
    [HR_Relocation_CarReturn_City] varchar(50) NULL,
    [HR_Relocation_CarReturn_State] varchar(50) NULL,
    [HR_Relocation_CarReturn_Place] varchar(50) NULL,
    [HR_Relocation_CarReturn_AddressLine1] varchar(50) NULL,
    [HR_Relocation_CarReturn_AddressLine2] varchar(50) NULL,
    [HR_Relocation_CarReturn_Zip] varchar(50) NULL,
    [HR_Relocation_RentalCarStartDate] varchar(50) NULL,
    [HR_Relocation_RentalCarEndDate] varchar(50) NULL,
    [HR_Relocation_RentalCarStartTime] varchar(50) NULL,
    [HR_Relocation_RentalCarEndTime] varchar(50) NULL,
    [HR_Relocation_MaxClientInvoice] varchar(50) NULL,
    [HR_Relocation_approving_manager] varchar(50) NULL,
    [HR_Relocation_Notes] varchar(5000) NULL,
    [HR_Recruiting_Manager] varchar(50) NULL,
    [HR_Recruiting_AccountExecutive] varchar(50) NULL,
    [HR_Recruiting_Recruiter] varchar(50) NULL,
    [HR_Recruiting_ResourceManager] varchar(50) NULL,
    [HR_Recruiting_Office] varchar(50) NULL,
    [HR_Recruiting_ReqNo] varchar(100) NULL,
    [HR_Recruiting_Direct] varchar(50) NULL,
    [HR_Recruiting_Replacement_For_GCIID] varchar(50) NULL,
    [HR_Recruiting_Replacement_For] varchar(50) NULL,
    [HR_Recruiting_Replacement_Reason] varchar(50) NULL,
    [HR_ClientInfo_ID] varchar(50) NULL,
    [HR_ClientInfo_Name] varchar(60) NULL,
    [HR_ClientInfo_DNB] varchar(50) NULL,
    [HR_ClientInfo_Sector] varchar(50) NULL,
    [HR_ClientInfo_Manager_ID] varchar(50) NULL,
    [HR_ClientInfo_Manager] varchar(50) NULL,
    [HR_ClientInfo_Phone] varchar(50) NULL,
    [HR_ClientInfo_Phone_Extn] varchar(50) NULL,
    [HR_ClientInfo_Email] varchar(50) NULL,
    [HR_ClientInfo_Fax] varchar(50) NULL,
    [HR_ClientInfo_Cell] varchar(50) NULL,
    [HR_ClientInfo_Pager] varchar(50) NULL,
    [HR_ClientInfo_Pager_Pin] varchar(50) NULL,
    [HR_ClientAgreements_SendTo] varchar(50) NULL,
    [HR_ClientAgreements_Phone] varchar(50) NULL,
    [HR_ClientAgreements_Phone_Extn] varchar(50) NULL,
    [HR_ClientAgreements_Email] varchar(50) NULL,
    [HR_ClientAgreements_Fax] varchar(50) NULL,
    [HR_ClientAgreements_Cell] varchar(50) NULL,
    [HR_ClientAgreements_Pager] varchar(50) NULL,
    [HR_ClientAgreements_Pager_Pin] varchar(50) NULL,
    [HR_Project_SendInvoicesTo] varchar(100) NULL,
    [HR_Project_AddressToSend1] varchar(150) NULL,
    [HR_Project_AddressToSend2] varchar(150) NULL,
    [HR_Project_City] varchar(50) NULL,
    [HR_Project_State] varchar(50) NULL,
    [HR_Project_Zip] varchar(50) NULL,
    [HR_Project_Phone] varchar(50) NULL,
    [HR_Project_Phone_Extn] varchar(50) NULL,
    [HR_Project_Email] varchar(50) NULL,
    [HR_Project_Fax] varchar(50) NULL,
    [HR_Project_Cell] varchar(50) NULL,
    [HR_Project_Pager] varchar(50) NULL,
    [HR_Project_Pager_Pin] varchar(50) NULL,
    [HR_Project_ST] varchar(50) NULL,
    [HR_Project_OT] varchar(50) NULL,
    [HR_Project_ST_Off] varchar(50) NULL,
    [HR_Project_OT_Off] varchar(50) NULL,
    [HR_Project_ST_Units] varchar(50) NULL,
    [HR_Project_OT_Units] varchar(50) NULL,
    [HR_Project_ST_Off_Units] varchar(50) NULL,
    [HR_Project_OT_Off_Units] varchar(50) NULL,
    [HR_Project_StartDate] varchar(50) NULL,
    [HR_Project_EndDate] varchar(50) NULL,
    [HR_Project_Location_AddressLine1] varchar(50) NULL,
    [HR_Project_Location_AddressLine2] varchar(50) NULL,
    [HR_Project_Location_City] varchar(50) NULL,
    [HR_Project_Location_State] varchar(50) NULL,
    [HR_Project_Location_Zip] varchar(50) NULL,
    [HR_Project_InvoicingTerms] varchar(50) NULL,
    [HR_Project_PaymentTerms] varchar(50) NULL,
    [HR_Project_EndClient_ID] varchar(50) NULL,
    [HR_Project_EndClient_Name] varchar(60) NULL,
    [HR_Project_EndClient_Sector] varchar(50) NULL,
    [HR_Accounts_Person] varchar(50) NULL,
    [HR_Accounts_PhoneNo] varchar(50) NULL,
    [HR_Accounts_PhoneNo_Extn] varchar(50) NULL,
    [HR_Accounts_Email] varchar(50) NULL,
    [HR_Accounts_FaxNo] varchar(50) NULL,
    [HR_Accounts_Cell] varchar(50) NULL,
    [HR_Accounts_Pager] varchar(50) NULL,
    [HR_Accounts_Pager_Pin] varchar(50) NULL,
    [HR_Project_Referrer_ID] varchar(50) NULL,
    [UserCreated] varchar(50) NULL,
    [DateCreated] varchar(50) NULL,
    [HR_Week_Cycle] int NULL,
    [Project_Name] varchar(255) NULL,
    [transition] varchar(50) NULL,
    [Is_OT_Allowed] varchar(50) NULL,
    [HR_Business_Type] varchar(50) NULL,
    [WebXl_EndClient_ID] varchar(50) NULL,
    [WebXl_EndClient_Name] varchar(60) NULL,
    [Client_Offer_Acceptance_Date] varchar(50) NULL,
    [Project_Type] varchar(50) NULL,
    [req_division] varchar(200) NULL,
    [Client_Compliance_Checks_Reqd] varchar(50) NULL,
    [HSU] varchar(50) NULL,
    [HSUDM] varchar(50) NULL,
    [Payroll_Location] varchar(50) NULL,
    [Is_DT_Allowed] varchar(50) NULL,
    [SBU] varchar(2) NULL,
    [BU] varchar(50) NULL,
    [Dept] varchar(2) NULL,
    [HCU] varchar(50) NULL,
    [Project_Category] varchar(50) NULL,
    [Delivery_Model] varchar(50) NULL,
    [BPOS_Project] varchar(3) NULL,
    [ER_Person] varchar(50) NULL,
    [Print_Invoice_Address1] varchar(100) NULL,
    [Print_Invoice_Address2] varchar(100) NULL,
    [Print_Invoice_City] varchar(50) NULL,
    [Print_Invoice_State] varchar(50) NULL,
    [Print_Invoice_Zip] varchar(50) NULL,
    [Mail_Invoice_Address1] varchar(100) NULL,
    [Mail_Invoice_Address2] varchar(100) NULL,
    [Mail_Invoice_City] varchar(50) NULL,
    [Mail_Invoice_State] varchar(50) NULL,
    [Mail_Invoice_Zip] varchar(50) NULL,
    [Project_Zone] varchar(50) NULL,
    [Emp_Identifier] varchar(50) NULL,
    [CRE_Person] varchar(50) NULL,
    [HR_Project_Location_Country] varchar(50) NULL,
    [Agency] varchar(50) NULL,
    [pwd] varchar(50) NULL,
    [PES_Doc_Sent] varchar(50) NULL,
    [PES_Confirm_Doc_Rcpt] varchar(50) NULL,
    [PES_Clearance_Rcvd] varchar(50) NULL,
    [PES_Doc_Sent_Date] varchar(50) NULL,
    [PES_Confirm_Doc_Rcpt_Date] varchar(50) NULL,
    [PES_Clearance_Rcvd_Date] varchar(50) NULL,
    [Inv_Pay_Terms_Notes] text NULL,
    [CBC_Notes] text NULL,
    [Benefits_Plan] varchar(50) NULL,
    [BillingCompany] varchar(50) NULL,
    [SPINOFF_CPNY] varchar(50) NULL,
    [Position_Type] varchar(50) NULL,
    [I9_Approver] varchar(50) NULL,
    [FP_BILL_Rate] varchar(50) NULL,
    [TSLead] varchar(50) NULL,
    [Inside_Sales] varchar(50) NULL,
    [Markup] varchar(50) NULL,
    [Maximum_Allowed_Markup] varchar(50) NULL,
    [Actual_Markup] varchar(50) NULL,
    [SCA_Hourly_Bill_Rate] varchar(50) NULL,
    [HR_Project_StartDate_Change_Reason] varchar(100) NULL,
    [source] varchar(50) NULL,
    [HR_Recruiting_VMO] varchar(50) NULL,
    [HR_Recruiting_Inside_Sales] varchar(50) NULL,
    [HR_Recruiting_TL] varchar(50) NULL,
    [HR_Recruiting_NAM] varchar(50) NULL,
    [HR_Recruiting_ARM] varchar(50) NULL,
    [HR_Recruiting_RM] varchar(50) NULL,
    [HR_Recruiting_ReqID] varchar(50) NULL,
    [HR_Recruiting_TAG] varchar(50) NULL,
    [DateUpdated] varchar(50) NULL,
    [UserUpdated] varchar(50) NULL,
    [Is_Swing_Shift_Associated_With_It] varchar(50) NULL,
    [FP_Bill_Rate_OT] varchar(50) NULL,
    [Not_To_Exceed_YESNO] varchar(10) NULL,
    [Exceed_YESNO] varchar(10) NULL,
    [Is_OT_Billable] varchar(5) NULL,
    [Is_premium_project_Associated_With_It] varchar(50) NULL,
    [ITSS_Business_Development_Manager] varchar(50) NULL,
    [Practice_type] varchar(50) NULL,
    [Project_billing_type] varchar(50) NULL,
    [Resource_billing_type] varchar(50) NULL,
    [Type_Consultant_category] varchar(50) NULL,
    [Unique_identification_ID_Doc] varchar(100) NULL,
    [Region1] varchar(100) NULL,
    [Region2] varchar(100) NULL,
    [Region1_percentage] varchar(10) NULL,
    [Region2_percentage] varchar(10) NULL,
    [Soc_Code] varchar(300) NULL,
    [Soc_Desc] varchar(300) NULL,
    [req_duration] int NULL,
    [Non_Billing_Type] varchar(50) NULL,
    [Worker_Entity_ID] varchar(30) NULL,
    [OraclePersonID] varchar(30) NULL,
    [Collabera_Email_ID] varchar(100) NULL,
    [Onsite_Consultant_Relationship_Manager] varchar(50) NULL,
    [HR_project_county] varchar(100) NULL,
    [EE_WF_Reasons] varchar(50) NULL,
    [GradeName] varchar(50) NULL,
    [ROLEFAMILY] varchar(50) NULL,
    [SUBDEPARTMENT] varchar(100) NULL,
    [MSProjectType] varchar(50) NULL,
    [NetsuiteProjectId] varchar(50) NULL,
    [NetsuiteCreatedDate] varchar(50) NULL,
    [NetsuiteModifiedDate] varchar(50) NULL,
    [StandardJobTitle] varchar(100) NULL,
    [community] varchar(100) NULL,
    [parent_Account_name] varchar(100) NULL,
    [Timesheet_Manager] varchar(255) NULL,
    [TimeSheetManagerType] varchar(255) NULL,
    [Timesheet_Manager_Phone] varchar(255) NULL,
    [Timesheet_Manager_Email] varchar(255) NULL,
    [HR_Project_Major_Group] varchar(255) NULL,
    [HR_Project_Minor_Group] varchar(255) NULL,
    [HR_Project_Broad_Group] varchar(255) NULL,
    [HR_Project_Detail_Group] varchar(255) NULL,
    [9Hours_Allowed] varchar(3) NULL,
    [9Hours_Effective_Date] varchar(50) NULL,
    load_timestamp DATETIME2,
    update_timestamp DATETIME2,
    source_system VARCHAR(100)
);

-- ... [DDL for all other tables as per the source structure, with metadata columns] ...

IF OBJECT_ID('Bronze.bz_Audit', 'U') IS NULL
CREATE TABLE Bronze.bz_Audit (
    record_id BIGINT,
    source_table VARCHAR(100),
    load_timestamp DATETIME2,
    processed_by VARCHAR(100),
    processing_time FLOAT,
    status VARCHAR(50)
);

-- =============================
-- Conceptual Data Model Diagram
-- =============================

-- | Table 1                        | Related Table                | Relationship Field (Key) |
-- |---------------------------------|------------------------------|--------------------------|
-- | bz_New_Monthly_HC_Report        | bz_report_392_all            | gci id                   |
-- | bz_SchTask                      | bz_Hiring_Initiator_Project_Info | GCI_ID (employee identifier) |
-- | bz_Timesheet_New                | bz_New_Monthly_HC_Report     | gci id                   |
-- | bz_vw_billing_timesheet_daywise_ne | bz_Timesheet_New           | GCI_ID                   |
-- | bz_vw_consultant_timesheet_daywise | bz_Timesheet_New           | GCI_ID                   |
-- | bz_DimDate                      | All date fields in other tables | Date, Holiday_Date, etc.|
-- | bz_holidays_Mexico              | bz_DimDate                   | Holiday_Date = Date      |
-- | bz_holidays_Canada              | bz_DimDate                   | Holiday_Date = Date      |
-- | bz_holidays                     | bz_DimDate                   | Holiday_Date = Date      |
-- | bz_holidays_India               | bz_DimDate                   | Holiday_Date = Date      |

-- =============================
-- API Cost
-- =============================
apiCost: 0.000000
